#!/usr/bin/env bash
#
# TL;DR: use this script ot start sbt if you're on NixOS >
# 18.03. Otherwise running just "sbt" should work.
#
# Sharry using Elm 0.18.0 and newer NixOSes have 0.19.0 installed.
#
# The build.nix creates a FHS environment that is also necessary to
# create the debian package.
#
# The LD_LIBRARY_PATH is set to empty, because there were strange
# errors when running elm-make:
#
#     relocation error: /usr/lib/libc.so.6: symbol
#     _dl_exception_create, version GLIBC_PRIVATE not defined in file
#     ld-linux-x86-64.so.2 with link time reference
#
# See here: https://github.com/NixOS/nixpkgs/issues/48780

nix-build build.nix && ./result/bin/sharry-sbt
