#!/usr/bin/env bash

cnt=''${SHARRY_CONTAINER:-sharry-dev}
if nixos-container list | grep $cnt > /dev/null; then
  echo "Destroying container $cnt"
  sudo nixos-container destroy $cnt
fi
echo "Creating and starting container $cnt ..."
sudo nixos-container create $cnt --flake .
sudo nixos-container start $cnt
