name: Release Nightly
on:
  push:
    branches:
      - "master"
jobs:
  release-nightly:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v26
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Set current version
        run:  echo "SHARRY_VERSION=$(cat version.sbt | grep version | cut -d= -f2 | xargs)" >> $GITHUB_ENV
      - name: sbt ci ${{ github.ref }}
        run: nix develop .#ci --command sbt ci
      - name: sbt make-pkg (${{ env.SHARRY_VERSION }})
        run: nix develop .#ci --command sbt make-pkg
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Sharry Nightly"
          files: |
            modules/restserver/target/sharry-restserver_${{ env.SHARRY_VERSION }}_all.deb
            modules/restserver/target/universal/sharry-restserver-${{ env.SHARRY_VERSION }}.zip
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker Images (${{ env.SHARRY_VERSION }})
        run: ./docker/build-images.sh ${{ env.SHARRY_VERSION }} --push
